language: java
jdk:
  - openjdk14
env:
  global:
    - CODECOV_TOKEN="28e3cf43-6869-4ffa-8822-57b6552f5938"

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      - angel.solodova@gmail.com
    on_success: never
    on_failure: always
